load_balancer:
  extends:
    file: ./node_modules/test-harness/docker-compose.yml
    service: load_balancer
  links:
    - web

web:
  extends:
    file: ./node_modules/test-harness/docker-compose.yml
    service: web
  build: ./web
  links:
    - beanstalk

worker:
  extends:
    file: ./node_modules/test-harness/docker-compose.yml
    service: worker
  build: ./worker
  links:
    - beanstalk

beanstalk:
  image: schickling/beanstalkd:latest
  expose:
    - "11300"
