load_balancer:
  build: ./load-balancer
  ports:
    - "80:80"
  environment:
    DOCKER_HOST:
    DOCKER_TLS_VERIFY:
    DOCKER_CERT_PATH: /etc/nginx/certs
  volumes:
    - $DOCKER_CERT_PATH:/etc/nginx/certs:ro
  links:
    - web

web:
  build: ./web
  expose:
    - "80"
  links:
    - beanstalk

worker:
  build: ./worker
  links:
    - beanstalk

beanstalk:
  image: "schickling/beanstalkd:latest"
  expose:
    - "11300"
